openapi: 3.0.0

info:
  title: foo
  version: '1'

servers:
- url: https://{subdomain}.site.com/{version}
  description: API for performing house price predictions.
  variables:
    subdomain:
      default: production
    version:
      enum:
        - v1
      default: v1

paths:

  /v1/predict:
    post:
      operationId: api.controller.predict
      requestBody:
        description: user to add to the system
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/PredictionRequest'
      responses:
        200:
          description: House Price Predictions

components:
  schemas:
    PredictionRequest:
      type: object
      properties:
        input_parameters:
          type: array
          items:
            type: string
          description: "List of the houses to get predictions for."
      required:
        - input_parameters

    ClientError:
      type: object
      properties:
        message:
          type: string
          description: "eg. There was something wrong with your request"
        reason:
          type: string
          description: 'eg. Id should be a string'
      required:
        - message
        - reason