version: '3'
services:
  ml_api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - PIP_EXTRA_INDEX_URL
    ports:
      - "5000:5000"   # expose webserver to localhost host:container
    command: bash -c "make run-service-development"
