version: '3'

volumes:
    prometheus_data: {}

services:
  webapp:
    build: .
    container_name: webapp 
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./:/application
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - 9090:9090
