{
 "title": "ML API Dashboard",
 "description": "Machine learning-specific metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Model Versions",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by(live_model, live_version, shadow_model, shadow_version, version)(model_version_details_info\n* on (instance, job) group_left(version)\npython_info)",
     "legendFormat": "{{model_version}}"
    }
   ]
  },
  {
   "title": "Average House Price Prediction Amount (USD)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(house_price_prediction_dollars_sum{job=\"ml_api\"}[5m])) / sum (rate(house_price_prediction_dollars_count{job=\"ml_api\"}[5m]))",
     "legendFormat": "Average Prediction Amount ($)"
    }
   ]
  },
  {
   "title": "Average House Price Prediction Amount (USD)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(house_price_prediction_dollars_sum{job=\"ml_api\"}[5m])) / sum (rate(house_price_prediction_dollars_count{job=\"ml_api\"}[5m]))",
     "legendFormat": "Average Prediction Amount ($)"
    }
   ]
  },
  {
   "title": "Average Prediction Delta (Drift?)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(house_price_prediction_dollars_sum{job=\"ml_api\"}[1h])) / sum (rate(house_price_prediction_dollars_count{job=\"ml_api\"}[1h])) \n- (sum (rate(house_price_prediction_dollars_sum{job=\"ml_api\"}[5m] offset 1h)) / sum(rate(house_price_prediction_dollars_count{job=\"ml_api\"}[5m] offset 1h)))",
     "legendFormat": "Average Prediction Rate / second"
    }
   ]
  },
  {
   "title": "Average Prediction Delta (Drift?)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(house_price_prediction_dollars_sum{job=\"ml_api\"}[1h])) / sum (rate(house_price_prediction_dollars_count{job=\"ml_api\"}[1h])) \n- (sum (rate(house_price_prediction_dollars_sum{job=\"ml_api\"}[5m] offset 1h)) / sum(rate(house_price_prediction_dollars_count{job=\"ml_api\"}[5m] offset 1h)))",
     "legendFormat": "Average Prediction Rate / second"
    }
   ]
  },
  {
   "title": "Min Prediction",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "house_price_gauge_dollars", "legendFormat": "Average Prediction Amount ($)" }
   ]
  },
  {
   "title": "Max Prediction",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "house_price_gauge_dollars", "legendFormat": "Average Prediction Amount ($)" }
   ]
  }
 ]
}